### ISSUE TITLE
Suggestion for a more helpful "More Info" text

### ISSUE THREAD

**Issue by 5T33Z0** [ChefKissInc/ForgedInvariant#3]
Hi and happy Holidays.

I've noticed that the "click here for more info" link in your repo's readme forwards to a github.io site which actually does not contain more information besides "CPU Support"

Maybe this is more informative:

> `ForgedInvariant` is a macOS kernel extension (kext) designed to synchronize the Time Stamp Counter (TSC) across all CPU cores in systems utilizing Intel or AMD processors. Proper TSC synchronization is crucial for the stable operation of macOS, as inconsistencies can lead to system instability or performance issues.
>
> This kext operates by aligning the TSC values across all CPU cores, ensuring that time-dependent processes function correctly. It is particularly beneficial for Hackintosh systems, where hardware configurations may not natively support macOS's expectations for TSC synchronization.

It would also be helpful to know when to use this this kext (symptoms, etc.)

**Comment by VisualEhrmanntraut** [comment]
Hello. Website updates are bottlenecked by adding translations at the moment, but once we are done with that, we can move forward to adding more content.
